[package]
name = "mayara-signalk-wasm"
version = "0.1.0"
edition = "2021"
description = "Mayara Radar SignalK WASM plugin"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
mayara-core = { path = "../mayara-core" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
